import type { Metadata } from 'next';
import RQProvider from '@/app/_components/RQProvider';
import RecoilProvider from '@/app/_components/RecoilProvider';
import { MSWComponent } from '@/app/_components/MSWComponent';
import * as stylex from '@stylexjs/stylex';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html {...stylex.props(styles.html, styles.reset)} lang="en">
      <body {...stylex.props(styles.reset, styles.body)}>
        <RecoilProvider>
          <RQProvider>
            <MSWComponent>{children}</MSWComponent>
          </RQProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}

const styles = stylex.create({
  html: {
    colorScheme: 'light dark',
  },
  reset: {
    minHeight: '100%',
    margin: 0,
    padding: 0,
  },
  body: {
    color: '#222',
  },
});
