import type { Metadata } from 'next';
import RQProvider from '@/app/_components/RQProvider';
import RecoilProvider from '@/app/_components/RecoilProvider';
import { MSWComponent } from '@/app/_components/MSWComponent';
import Header from '@/app/_components/Header';

import './globals.css';
import Footer from './_components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RecoilProvider>
          <RQProvider>
            <MSWComponent>
              <Header />
              {children}
              <Footer />
            </MSWComponent>
          </RQProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
